apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.1
    replicas: 2 # Adjusted number of Kafka brokers
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          externalTrafficPolicy: Cluster
          # loadBalancerIP: "YOUR_DESIRED_EXTERNAL_IP"
    config:
      offsets.topic.replication.factor: 2 # Adjusted for the new number of replicas
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 2 # Adjusted to match the number of replicas
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "1"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 2 # Assuming you want to keep Zookeeper replicas as is
    storage:
      type: ephemeral
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
  entityOperator:
    topicOperator: {}
    userOperator: {}
